apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-node-permissions
  labels:
    {{- include "besu-sandbox.labels" . | nindent 4 }}
data:
  nodes-allowlist.yml: |
{{ include "besu-sandbox.nodesAllowlist" . | indent 4 }}
  {{- if .Values.permissioning.accounts.enabled }}
  accounts-allowlist.toml: |
{{ include "besu-sandbox.accountsAllowlist" . | indent 4 }}
  {{- end }}
