apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-validators
  labels:
    {{- include "besu-sandbox.labels" . | nindent 4 }}
data:
{{- range $i, $v := .Values.validators }}
  validator{{ add $i 1 }}PubKey: {{ $v.pubKey | quote }}
{{- end }}
