{{- if eq (include "besu-sandbox.validatorKeysSource" .) "externalSecrets" }}
{{- range $i, $v := $.Values.validators }}
{{- $n := add $i 1 }}
{{- $key := $.Values.validatorKeys.externalSecrets.remoteRef.keyTemplate | replace "{{n}}" ($n | toString) }}
{{- $target := include "besu-sandbox.validatorKeySecretName" (dict "root" $ "n" $n) }}
---
apiVersion: {{ $.Values.validatorKeys.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ $target }}
  labels:
    {{- include "besu-sandbox.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $.Values.validatorKeys.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ $.Values.validatorKeys.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ $.Values.validatorKeys.externalSecrets.secretStoreRef.kind }}
  target:
    name: {{ $target }}
    creationPolicy: Owner
  data:
    - secretKey: {{ $.Values.validatorKeys.externalSecrets.target.dataKey }}
      remoteRef:
        key: {{ $key | quote }}
        {{- with $.Values.validatorKeys.externalSecrets.remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
{{- end }}
{{- end }}
