{{- if eq (include "besu-sandbox.validatorKeysSource" .) "values" }}
{{- range $i, $v := .Values.validators }}
{{- $n := add $i 1 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "besu-sandbox.validatorKeySecretName" (dict "root" $ "n" $n) }}
  labels:
    {{- include "besu-sandbox.labels" $ | nindent 4 }}
type: Opaque
stringData:
  nodekey: |-
    {{ $v.nodeKey }}
{{- end }}
{{- end }}
